/**
 * API Error Codes
 *
 * Standardized error codes for consistent API error responses.
 * Format: CATEGORY_NNNN where NNNN is a unique number within the category.
 */
export const ErrorCodes = {
  // Authentication (1xxx)
  AUTH_INVALID_CREDENTIALS: 'AUTH_1001',
  AUTH_TOKEN_EXPIRED: 'AUTH_1002',
  AUTH_TOKEN_INVALID: 'AUTH_1003',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_1004',
  AUTH_UNAUTHORIZED: 'AUTH_1005',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_1006',
  AUTH_EMAIL_EXISTS: 'AUTH_1007',
  AUTH_ACCOUNT_LOCKED: 'AUTH_1008',
  AUTH_ACCOUNT_DISABLED: 'AUTH_1009',
  AUTH_MFA_REQUIRED: 'AUTH_1010',
  AUTH_MFA_INVALID: 'AUTH_1011',
  AUTH_MFA_NOT_CONFIGURED: 'AUTH_1012',
  AUTH_MFA_ALREADY_ENABLED: 'AUTH_1013',
  AUTH_PASSWORD_TOO_WEAK: 'AUTH_1014',
  AUTH_PASSWORD_SAME_AS_OLD: 'AUTH_1015',
  AUTH_EMAIL_VERIFICATION_EXPIRED: 'AUTH_1016',
  AUTH_EMAIL_VERIFICATION_INVALID: 'AUTH_1017',
  AUTH_EMAIL_ALREADY_VERIFIED: 'AUTH_1018',
  AUTH_SESSION_NOT_FOUND: 'AUTH_1019',
  AUTH_BACKUP_CODE_INVALID: 'AUTH_1020',
  AUTH_BACKUP_CODES_EXHAUSTED: 'AUTH_1021',
  AUTH_OAUTH_PROVIDER_ERROR: 'AUTH_1022',
  AUTH_APPLE_ID_TOKEN_INVALID: 'AUTH_1023',
  AUTH_SUSPICIOUS_ACTIVITY: 'AUTH_1024',
  AUTH_TOO_MANY_ATTEMPTS: 'AUTH_1025',
  AUTH_GOOGLE_EMAIL_NOT_VERIFIED: 'AUTH_1026',

  // Validation (2xxx)
  VALIDATION_ERROR: 'VAL_2001',
  VALIDATION_REQUIRED_FIELD: 'VAL_2002',
  VALIDATION_INVALID_FORMAT: 'VAL_2003',
  VALIDATION_INVALID_VALUE: 'VAL_2004',

  // Resources (3xxx)
  RESOURCE_NOT_FOUND: 'RES_3001',
  RESOURCE_ALREADY_EXISTS: 'RES_3002',
  RESOURCE_CONFLICT: 'RES_3003',
  RESOURCE_FORBIDDEN: 'RES_3004',

  // Rate Limiting (4xxx)
  RATE_LIMIT_EXCEEDED: 'RATE_4001',

  // AI Service (5xxx)
  AI_SERVICE_ERROR: 'AI_5001',
  AI_RATE_LIMIT: 'AI_5002',
  AI_CONTEXT_TOO_LARGE: 'AI_5003',

  // External Services (6xxx)
  EXTERNAL_SERVICE_ERROR: 'EXT_6001',
  EXTERNAL_SERVICE_TIMEOUT: 'EXT_6002',

  // Finance (7xxx)
  FINANCE_INSUFFICIENT_DATA: 'FIN_7001',
  FINANCE_CALCULATION_ERROR: 'FIN_7002',
  FINANCE_SNAPSHOT_NOT_FOUND: 'FIN_7003',
  FINANCE_USER_NOT_FOUND: 'FIN_7004',
  FINANCE_INVALID_DATA: 'FIN_7005',
  FINANCE_SIMULATION_ERROR: 'FIN_7006',
  FINANCE_INVALID_SIMULATION_INPUT: 'FIN_7007',
  FINANCE_NO_ACTIVE_GOAL: 'FIN_7008',

  // Shark Auditor (8xxx)
  SHARK_SUBSCRIPTION_NOT_FOUND: 'SHARK_8001',
  SHARK_INSUFFICIENT_DATA: 'SHARK_8002',
  SHARK_AUDIT_ERROR: 'SHARK_8003',
  SHARK_CANCELLATION_ERROR: 'SHARK_8004',
  SHARK_DUPLICATE_DECISION: 'SHARK_8005',

  // Server (9xxx)
  INTERNAL_ERROR: 'SRV_9001',
  SERVICE_UNAVAILABLE: 'SRV_9002',
  DATABASE_ERROR: 'SRV_9003',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
