/**
 * Story Cards Interfaces
 *
 * Type definitions for the Story Cards viral sharing system.
 */

import { StoryCardType, SharePlatform } from '@prisma/client';

/**
 * Story Card data structure
 */
export interface StoryCard {
  id: string;
  type: StoryCardType;
  userId: string;
  generatedAt: Date;
  headline: string;
  subheadline: string;
  keyMetric: {
    label: string;
    value: string;
  };
  quote?: string;
  shareUrl: string;
  platforms: SharePlatform[];
  hashtags: string[];
  gradient: [string, string];
  anonymizeAmounts: boolean;
  viewCount: number;
  referralCode: string;
  sourceId?: string;
  expiresAt?: Date;
  createdAt: Date;
}

/**
 * Privacy settings for card generation
 */
export interface PrivacySettings {
  anonymizeAmounts: boolean;        // Default: true - show percentages instead of amounts
  revealActualNumbers: boolean;     // Default: false - opt-in to show real amounts
  includePersonalData: boolean;     // Default: false - opt-in to include name/goals
  requirePreview: boolean;          // Default: true - show preview before sharing
}

/**
 * Card content generated by calculator
 */
export interface CardContent {
  headline: string;
  subheadline: string;
  keyMetric: {
    label: string;
    value: string;
  };
  quote?: string;
  hashtags: string[];
  gradient: [string, string];
  gradientIndex: number; // Index of selected gradient for A/B testing
}

/**
 * Gradient performance data for A/B testing analytics
 */
export interface GradientPerformance {
  gradientIndex: number;
  cardCount: number;
  totalViews: number;
  avgViews: number;
}

/**
 * Source data for Future Self card type
 */
export interface FutureSelfSource {
  letterId: string;
  content: string;
  userAge: number;
  futureAge: number;
  currentNetWorth: number;
  wealthDifference20yr: number;
  currentSavingsRate: number;
  optimizedSavingsRate: number;
  createdAt: Date;
}

/**
 * Source data for Commitment card type
 */
export interface CommitmentSource {
  contractId: string;
  goalName: string;
  stakeType: string;
  stakeAmount: number | null;
  deadline: Date;
  successProbability: number;
  createdAt: Date;
}

/**
 * Source data for Milestone card type
 */
export interface MilestoneSource {
  goalId: string;
  goalName: string;
  targetAmount: number;
  currentAmount: number;
  daysToAchieve: number;
  completedAt: Date;
  category: string;
}

/**
 * Source data for Recovery card type
 */
export interface RecoverySource {
  sessionId: string;
  category: string;
  overspendAmount: number;
  previousProbability: number;
  newProbability: number;
  probabilityRestored: number;
  selectedPath: string;
  completedAt: Date;
}

/**
 * Union type for all source data types
 */
export type SourceData =
  | { type: 'FUTURE_SELF'; data: FutureSelfSource }
  | { type: 'COMMITMENT'; data: CommitmentSource }
  | { type: 'MILESTONE'; data: MilestoneSource }
  | { type: 'RECOVERY'; data: RecoverySource };

/**
 * Input for generating a story card
 */
export interface GenerateCardInput {
  type: StoryCardType;
  sourceId: string;
  idempotencyKey?: string;
  anonymizeAmounts?: boolean;
  revealActualNumbers?: boolean;
  includePersonalData?: boolean;
}

/**
 * Input for tracking share events
 */
export interface TrackShareInput {
  platform: SharePlatform;
  ipAddress?: string;
  userAgent?: string;
}

/**
 * Share event data
 */
export interface ShareEventData {
  id: string;
  cardId: string;
  platform: SharePlatform;
  sharedAt: Date;
  referralCode: string;
}

/**
 * Public share page data
 */
export interface SharePageData {
  card: {
    id: string;
    type: StoryCardType;
    headline: string;
    subheadline: string;
    keyMetric: {
      label: string;
      value: string;
    };
    quote?: string;
    gradient: [string, string];
    hashtags: string[];
    viewCount: number;
    createdAt: Date;
  };
  referralCode: string;
  ogMeta: {
    title: string;
    description: string;
    image?: string;
    url: string;
  };
}

/**
 * Viral metrics for analytics
 */
export interface ViralMetrics {
  totalCards: number;
  totalShares: number;
  sharesByPlatform: Record<SharePlatform, number>;
  totalViews: number;
  signupsFromShares: number;
  viralCoefficient: number;  // signups / shares ratio
  topPerformingType: StoryCardType | null;
  sharesByType: Record<StoryCardType, number>;  // actual share events per card type
  cardsByType: Record<StoryCardType, number>;   // count of cards per type
  averageViewsPerCard: number;
  conversionRate: number;    // views that result in shares
}

/**
 * Pagination parameters
 */
export interface PaginationParams {
  page?: number;
  limit?: number;
}

/**
 * Paginated response
 */
export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
    hasMore: boolean;
  };
}

/**
 * Card response with full details
 */
export interface StoryCardResponse {
  id: string;
  type: StoryCardType;
  headline: string;
  subheadline: string;
  keyMetric: {
    label: string;
    value: string;
  };
  quote?: string;
  shareUrl: string;
  platforms: string[];
  hashtags: string[];
  gradient: [string, string];
  anonymizeAmounts: boolean;
  viewCount: number;
  referralCode: string;
  sourceId?: string;
  expiresAt?: Date;
  createdAt: Date;
}

/**
 * Card list item (lighter version for lists)
 */
export interface StoryCardListItem {
  id: string;
  type: StoryCardType;
  headline: string;
  shareUrl: string;
  viewCount: number;
  referralCode: string;
  createdAt: Date;
}

/**
 * Delete card response
 */
export interface DeleteCardResponse {
  success: boolean;
  cardId: string;
  deleteType: 'soft' | 'hard';
  deletedAt: Date;
  message?: string;
}

/**
 * Input for updating a story card
 */
export interface UpdateCardInput {
  anonymizeAmounts?: boolean;
  revealActualNumbers?: boolean;
  includePersonalData?: boolean;
  regenerateContent?: boolean;
}

/**
 * Update card response
 */
export interface UpdateCardResponse extends StoryCardResponse {
  updated: boolean;
  regenerated?: boolean;
}

/**
 * Input for previewing a story card
 */
export interface PreviewCardInput {
  type: StoryCardType;
  sourceId: string;
  anonymizeAmounts?: boolean;
  revealActualNumbers?: boolean;
  includePersonalData?: boolean;
}

/**
 * Preview card response (not saved to database)
 */
export interface PreviewCardResponse {
  preview: true;
  type: StoryCardType;
  headline: string;
  subheadline: string;
  keyMetric: {
    label: string;
    value: string;
  };
  quote?: string;
  platforms: string[];
  hashtags: string[];
  gradient: [string, string];
  anonymizeAmounts: boolean;
  sourceId?: string;
  generatedAt: Date;
}

/**
 * Item in bulk generate request
 */
export interface BulkGenerateItem {
  type: StoryCardType;
  sourceId: string;
  anonymizeAmounts?: boolean;
}

/**
 * Failed item in bulk operation
 */
export interface BulkOperationFailedItem {
  id?: string;
  sourceId?: string;
  type?: StoryCardType;
  reason: string;
}

/**
 * Result of bulk delete operation
 */
export interface BulkDeleteResult {
  deleted: string[];
  failed: { id: string; reason: string }[];
  deleteType: 'soft' | 'hard';
  processedAt: Date;
  summary: {
    requested: number;
    deleted: number;
    failed: number;
  };
}

/**
 * Result of bulk generate operation
 */
export interface BulkGenerateResult {
  generated: string[];
  failed: { sourceId: string; type: StoryCardType; reason: string }[];
  processedAt: Date;
  summary: {
    requested: number;
    generated: number;
    failed: number;
  };
}
